### ISSUE TITLE
Getting a segmentaiton fault running letsencrypt-auto --apache

### ISSUE THREAD

**Issue by CuZnDragon** [certbot/certbot#1976]
This is the debug output
./letsencrypt-auto --verbose --debug --apache
Bootstrapping dependencies for Debian-based OSes...
Hit:1 http://ftp.us.debian.org/debian sid InRelease
Hit:2 http://deb-multimedia.org sid InRelease  
Reading package lists... Done  
Reading package lists... Done
Building dependency tree  
Reading state information... Done
libaugeas0 is already the newest version (1.2.0-0.3).
ca-certificates is already the newest version (20151214).
dialog is already the newest version (1.2-20150920-1).
gcc is already the newest version (4:5.3.1-1).
git is already the newest version (1:2.6.4-1).
libffi-dev is already the newest version (3.2.1-4).
libssl-dev is already the newest version (1.0.2e-1).
python is already the newest version (2.7.11-1).
python-dev is already the newest version (2.7.11-1).
python-virtualenv is already the newest version (1.11.6+ds-1).
virtualenv is already the newest version (1.11.6+ds-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Creating virtual environment...
Running virtualenv with interpreter /usr/bin/python2.7
New python executable in /root/.local/share/letsencrypt/bin/python2.7
Also creating executable in /root/.local/share/letsencrypt/bin/python
Installing setuptools, pip...done.
Updating letsencrypt and virtual environment dependencies...
Downloading/unpacking setuptools from https://pypi.python.org/packages/3.5/s/setuptools/setuptools-19.1.1-py2.py3-none-any.whl#md5=29d589434b067e67c95d6625a211909e
  Downloading setuptools-19.1.1-py2.py3-none-any.whl (463kB): 463kB downloaded
Installing collected packages: setuptools
  Found existing installation: setuptools 18.8
    Uninstalling setuptools:
      Successfully uninstalled setuptools
Successfully installed setuptools
Cleaning up...
Downloading/unpacking pip from https://pypi.python.org/packages/py2.py3/p/pip/pip-7.1.2-py2.py3-none-any.whl#md5=5ff9fec0be479e4e36df467556deed4d
  Downloading pip-7.1.2-py2.py3-none-any.whl (1.1MB): 1.1MB downloaded
Installing collected packages: pip
  Found existing installation: pip 1.5.6
    Uninstalling pip:
      Successfully uninstalled pip
Successfully installed pip
Cleaning up...
Collecting letsencrypt
  Using cached letsencrypt-0.1.1-py2-none-any.whl
Collecting letsencrypt-apache
  Using cached letsencrypt_apache-0.1.1-py2-none-any.whl
Collecting ConfigArgParse from git+https://github.com/kuba/ConfigArgParse.git@python2.6-0.9.3#egg=ConfigArgParse (from -r ./py26reqs.txt (line 1))
  Cloning https://github.com/kuba/ConfigArgParse.git (to python2.6-0.9.3) to /tmp/pip-build-TsHdgL/ConfigArgParse
Collecting zope.interface (from letsencrypt)
  Using cached zope.interface-4.1.3.tar.gz
Requirement already up-to-date: setuptools in /root/.local/share/letsencrypt/lib/python2.7/site-packages (from letsencrypt)
Collecting python2-pythondialog>=3.2.2rc1 (from letsencrypt)
  Using cached python2-pythondialog-3.3.0.tar.bz2
Collecting PyOpenSSL (from letsencrypt)
  Using cached pyOpenSSL-0.15.1-py2.py3-none-any.whl
Collecting requests (from letsencrypt)
  Using cached requests-2.9.1-py2.py3-none-any.whl
Collecting cryptography>=0.7 (from letsencrypt)
  Using cached cryptography-1.1.2.tar.gz
Collecting parsedatetime (from letsencrypt)
  Using cached parsedatetime-1.5-py2-none-any.whl
Collecting configobj (from letsencrypt)
  Using cached configobj-5.0.6.tar.gz
Collecting pytz (from letsencrypt)
  Using cached pytz-2015.7-py2.py3-none-any.whl
Collecting psutil>=2.1.0 (from letsencrypt)
  Using cached psutil-3.3.0.tar.gz
Collecting six (from letsencrypt)
  Using cached six-1.10.0-py2.py3-none-any.whl
Collecting acme==0.1.1 (from letsencrypt)
  Using cached acme-0.1.1-py2-none-any.whl
Collecting zope.component (from letsencrypt)
  Using cached zope.component-4.2.2.tar.gz
Collecting mock (from letsencrypt)
  Using cached mock-1.3.0-py2.py3-none-any.whl
Collecting pyrfc3339 (from letsencrypt)
  Using cached pyRFC3339-1.0-py2.py3-none-any.whl
Collecting python-augeas (from letsencrypt-apache)
  Using cached python-augeas-0.5.0.tar.gz
Collecting idna>=2.0 (from cryptography>=0.7->letsencrypt)
  Using cached idna-2.0-py2.py3-none-any.whl
Collecting pyasn1>=0.1.8 (from cryptography>=0.7->letsencrypt)
  Using cached pyasn1-0.1.9-py2.py3-none-any.whl
Collecting enum34 (from cryptography>=0.7->letsencrypt)
  Using cached enum34-1.1.1.tar.gz
Collecting ipaddress (from cryptography>=0.7->letsencrypt)
  Using cached ipaddress-1.0.15-py27-none-any.whl
Collecting cffi>=1.1.0 (from cryptography>=0.7->letsencrypt)
  Using cached cffi-1.4.2.tar.gz
Collecting ndg-httpsclient (from acme==0.1.1->letsencrypt)
  Using cached ndg_httpsclient-0.4.0.tar.gz
Collecting werkzeug (from acme==0.1.1->letsencrypt)
  Using cached Werkzeug-0.11.3-py2.py3-none-any.whl
Collecting zope.event (from zope.component->letsencrypt)
  Using cached zope.event-4.1.0.tar.gz
Collecting funcsigs (from mock->letsencrypt)
  Using cached funcsigs-0.4-py2.py3-none-any.whl
Collecting pbr>=0.11 (from mock->letsencrypt)
  Using cached pbr-1.8.1-py2.py3-none-any.whl
Collecting pycparser (from cffi>=1.1.0->cryptography>=0.7->letsencrypt)
  Using cached pycparser-2.14.tar.gz
Installing collected packages: zope.interface, python2-pythondialog, six, idna, pyasn1, enum34, ipaddress, pycparser, cffi, cryptography, PyOpenSSL, requests, parsedatetime, configobj, pytz, psutil, ndg-httpsclient, werkzeug, funcsigs, pbr, mock, pyrfc3339, acme, zope.event, zope.component, ConfigArgParse, letsencrypt, python-augeas, letsencrypt-apache
  Running setup.py install for zope.interface
  Running setup.py install for python2-pythondialog
  Running setup.py install for enum34
  Running setup.py install for pycparser
  Running setup.py install for cffi
  Running setup.py install for cryptography
  Running setup.py install for configobj
  Running setup.py install for psutil
  Running setup.py install for ndg-httpsclient
  Running setup.py install for zope.event
  Running setup.py install for zope.component
  Running setup.py install for ConfigArgParse
  Running setup.py install for python-augeas
Successfully installed ConfigArgParse-0.9.3 PyOpenSSL-0.15.1 acme-0.1.1 cffi-1.4.2 configobj-5.0.6 cryptography-1.1.2 enum34-1.1.1 funcsigs-0.4 idna-2.0 ipaddress-1.0.15 letsencrypt-0.1.1 letsencrypt-apache-0.1.1 mock-1.3.0 ndg-httpsclient-0.4.0 parsedatetime-1.5 pbr-1.8.1 psutil-3.3.0 pyasn1-0.1.9 pycparser-2.14 pyrfc3339-1.0 python-augeas-0.5.0 python2-pythondialog-3.3.0 pytz-2015.7 requests-2.9.1 six-1.10.0 werkzeug-0.11.3 zope.component-4.2.2 zope.event-4.1.0 zope.interface-4.1.3
Segmentation fault
Running with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt --verbose --debug --apache
Segmentation fault

**Comment by pde** [comment]
What OS / version / hardware are you running this on?  There are two segfaults there; it would be good to know which command the first of them is occurring in.  One way to get a definite answer there would be:

* `rm -rf /root/.local/share/letsencrypt/`
* edit the `letsencrypt-auto` script to make the first line run the shell with `-xe` rather than just `-e`
* run `letsencrypt-auto` again, it should show the exact step at which the first segfault occurred
* run that step manually, under `strace`?

**Comment by pde** [comment]
(Steps 1-3 would get us the exact command that's segfaulting; Step 4 would get us what's actually happening to cause the crash)

**Comment by CuZnDragon** [comment]
I am running this on Debian Sid and the latest git pull for letsencrypt.

+ + /root/.local/share/letsencrypt/bin/pip freeze
grep -q letsencrypt-nginx
Segmentation fault
+ echo Running with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt --debug --verbose --apache
Running with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt --debug --verbose --apache
+ /root/.local/share/letsencrypt/bin/letsencrypt --debug --verbose --apache
Segmentation fault

Running strace /root/.local/share/letsencrypt/bin/pip freeze

stat("/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/_conditional", 0x7ffe7df441e0) = -1 ENOENT (No such file or directory)
open("/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/_conditional.x86_64-linux-gnu.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/_conditional.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/_conditionalmodule.so", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/_conditional.py", O_RDONLY) = 12
fstat(12, {st_mode=S_IFREG|0644, st_size=12178, ...}) = 0
open("/root/.local/share/letsencrypt/local/lib/python2.7/site-packages/cryptography/hazmat/bindings/openssl/_conditional.pyc", O_RDONLY) = 14
fstat(14, {st_mode=S_IFREG|0644, st_size=11132, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb6c743f000
read(14, "\3\363\r\nw\261xVc\0\0\0\0\0\0\0\0T\0\0\0@`\1\0s\326\4\0\0d\0"..., 4096) = 4096
fstat(14, {st_mode=S_IFREG|0644, st_size=11132, ...}) = 0
read(14, "ivateKey_biot\17\0\0\0i2o_ECPublicKey"..., 4096) = 4096
read(14, "tography_HAS_NEXTPROTONEGt(\0\0\0SS"..., 4096) = 2940
read(14, "", 4096)                      = 0
close(14)                               = 0
munmap(0x7fb6c743f000, 4096)            = 0
close(12)                               = 0
open("/proc/self/status", O_RDONLY)     = 12
fstat(12, {st_mode=S_IFREG|0444, st_size=0, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb6c743f000
read(12, "Name:\tpip\nState:\tR (running)\nTgi"..., 1024) = 856
read(12, "", 1024)                      = 0
close(12)                               = 0
munmap(0x7fb6c743f000, 4096)            = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fb6c743f000
--- SIGSEGV {si_signo=SIGSEGV, si_code=SEGV_MAPERR, si_addr=0x80} ---
+++ killed by SIGSEGV +++
Segmentation fault


Or do I need to go back farther to get the info you need?

**Comment by demonicpagan** [comment]
I am running into this same issue when trying to update a certificate of mine. Since my strace is massive and I've included all the other data, I've just posted it into a gist: https://gist.github.com/demonicpagan/7f72908aeccef5223041

I am running a Debian 9.0 Linux server running a fresh git pull

**Comment by e2jk** [comment]
Same here, running a Debian Testing with all available updates installed.

I've gotten the latest files from git, cd'd to that directory, and ran `./letsencrypt-auto`. It downloaded about 100Mb of Debian packages, the last few lines are like this:

```
Setting up python-pip-whl (1.5.6-7) ...
Setting up python-virtualenv (1.11.6+ds-1) ...
Setting up python3-virtualenv (1.11.6+ds-1) ...
Setting up virtualenv (1.11.6+ds-1) ...
Processing triggers for libc-bin (2.21-4) ...
Creating virtual environment...
Updating letsencrypt and virtual environment dependencies......Segmentation fault
```

When trying to run it again:
```
$ ./letsencrypt-auto --verbose --debug
Updating letsencrypt and virtual environment dependencies...
Segmentation fault
```

Let me know what extra information I can provide.

**Comment by e2jk** [comment]
Weird... So I've got my sudo setup to not ask for password. The first time I ran `./letsencrypt-auto`, as the Debian packages got installed it looked to me that the script was able to get sudo rights allright.

I tried to rerun the command, this time with an explicit sudo (`sudo $ ./letsencrypt-auto --verbose --debug`), and that got me much farther than in my previous post (apparently installing a bunch of stuff from pip), but still ending with a segmentation fault:

```
Collecting pbr>=0.11 (from mock->letsencrypt)
  Downloading pbr-1.8.1-py2.py3-none-any.whl (89kB)
    100% |################################| 90kB 3.5MB/s
Collecting pycparser (from cffi>=1.1.0->cryptography>=0.7->letsencrypt)
  Downloading pycparser-2.14.tar.gz (223kB)
    100% |################################| 225kB 1.4MB/s
Installing collected packages: zope.interface, python2-pythondialog, six, idna, pyasn1, enum34, ipaddress, pycparser, cffi, cryptography, PyOpenSSL, requests, parsedatetime, configobj, pytz, psutil, ndg-httpsclient, werkzeug, funcsigs, pbr, mock, pyrfc3339, acme, zope.event, zope.component, ConfigArgParse, letsencrypt, python-augeas, letsencrypt-apache
  Running setup.py install for zope.interface
  Running setup.py install for python2-pythondialog
  Running setup.py install for enum34
  Running setup.py install for pycparser
  Running setup.py install for cffi
  Running setup.py install for cryptography
  Running setup.py install for configobj
  Running setup.py install for psutil
  Running setup.py install for ndg-httpsclient
  Running setup.py install for zope.event
  Running setup.py install for zope.component
  Running setup.py install for ConfigArgParse
  Running setup.py install for python-augeas
Successfully installed ConfigArgParse-0.10.0 PyOpenSSL-0.15.1 acme-0.1.1 cffi-1.4.2 configobj-5.0.6 cryptography-1.1.2 enum34-1.1.2 funcsigs-0.4 idna-2.0 ipaddress-1.0.16 letsencrypt-0.1.1 letsencrypt-apache-0.1.1 mock-1.3.0 ndg-httpsclient-0.4.0 parsedatetime-1.5 pbr-1.8.1 psutil-3.3.0 pyasn1-0.1.9 pycparser-2.14 pyrfc3339-1.0 python-augeas-0.5.0 python2-pythondialog-3.3.0 pytz-2015.7 requests-2.9.1 six-1.10.0 werkzeug-0.11.3 zope.component-4.2.2 zope.event-4.1.0 zope.interface-4.1.3
Segmentation fault
Requesting root privileges to run with virtualenv: /root/.local/share/letsencrypt/bin/letsencrypt --verbose --debug
Segmentation fault
```

Running it once again with `sudo` does end just as in my previous post again though:

```
$ sudo ./letsencrypt-auto --verbose --debug
Updating letsencrypt and virtual environment dependencies...
Segmentation fault
```

**Comment by alex** [comment]
I strongly suspect this is caused by a GCC bug in debian testing, documented here: https://github.com/pyca/cryptography/issues/2592#issuecomment-167426382

**Comment by e2jk** [comment]
Based on [these](https://community.letsencrypt.org/t/segmentation-fault/7134/4) [two](https://community.letsencrypt.org/t/cffi-is-broken-if-compiled-with-gcc-5-3-1/7938/2) threads on the LE discourse, it seems that the reason for this bug might be an issue with GCC 5.3.1 (which I indeed have installed on my machine). [Looks like](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=69037) this might already be fixed in the development branch of gcc, but not yet released.

**Comment by agropper** [comment]
Working with FreedomBox on a VM on Debian-testing, I'm just getting the Segmentation fault now but earlier, I got: 

fbx@MyAS:~/letsencrypt$ ./letsencrypt-auto --apache
Updating letsencrypt and virtual environment dependencies.....Command "/home/fbx/.local/share/letsencrypt/bin/python2.7 -c "import setuptools, tokenize;__file__='/tmp/user/1001/pip-build-m794u0/cryptography/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/user/1001/pip-Fpnu4C-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/fbx/.local/share/letsencrypt/include/site/python2.7/cryptography" failed with error code 1 in /tmp/user/1001/pip-build-m794u0/cryptography

I've shared the complete terminal log here: https://dl.dropboxusercontent.com/u/8909568/freedombox-letsencrypt-auto.log.txt

Is his helpful? I'm happy to grant access to the FreedomBox VM if anyone asks me directly.

Adrian

**Comment by e2jk** [comment]
@agropper FYI I got around this issue by installing the software from the Debian repository (package `letsencrypt`). Since you're working on a Freedombox (i.e. Debian) this might be a good workaround for now.

**Comment by agropper** [comment]
Emilien,

Thanks for the suggestion. I'm a newbie to Debian. Can you give me a bit
more detail or point me somewhere?

Thanks,

Adrian

On Saturday, January 2, 2016, Emilien Klein <notifications@github.com>
wrote:

> @agropper <https://github.com/agropper> FYI I got around this issue by
> installing the software from the Debian repository (package letsencrypt).
> Since you're working on a Freedombox (i.e. Debian) this might be a good
> workaround for now.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/letsencrypt/letsencrypt/issues/1976#issuecomment-168449868>
> .
>


-- 

Adrian Gropper MD

PROTECT YOUR FUTURE - RESTORE Health Privacy!
HELP us fight for the right to control personal health data.
DONATE: http://patientprivacyrights.org/donate-2/

**Comment by e2jk** [comment]
Done via email.

**Comment by agropper** [comment]
Success! I used the Debian instructions for apache. Had to log in as root from the VM console and stop apache2. It asked about "no names were found..." which I found a bit troubling but I accepted the default.

Incredibly easy. Fabulous job Let's Encrypt. Thank you!

**Comment by itoffshore** [comment]
Running a Debian Jessie `lxc` container inside Debian is fine - but running the exact same Jessie container inside Alpine Linux also segfaults:
```
[160680.595926] pip[30690]: segfault at 0 ip 0000744a5995a99b sp 00007c8f6667b848 error 6 in libffi.so.6.0.2[744a59955000+7000]
[160680.595960] grsec: Segmentation fault occurred at            (nil) in /home/stuart/.local/share/letsencrypt/bin/pip[pip:30690] 
```
Error 6 = `The cause was a user-mode write resulting in no page being found` [source](http://rgeissert.blogspot.nl/p/segmentation-fault-error.html)

(run `dmesg` after the `segfault` occurs)

**Comment by mcassaniti** [comment]
Seeing this issue still on Alpine Linux 3.7, even if I install certbot using pip. The issue I'm seeing is an EPERM with mmap. I'm running certbot inside a container.

**Comment by bmw** [comment]
@mcassaniti, I suspect the problem you're hitting is the one described in #5737.

I think the issue in Debian has been resolved though so I'm closing this issue. Please let me know if you think I missed something!

**Comment by mcassaniti** [comment]
The issue eventually seemed to be the Python cryptography module in Alpine Linux 3.7. An upgrade to 3.8 didn't seem to have this issue.
