### ISSUE TITLE
Slackware Certbot packages should conflict with the old letsencrypt ones

### ISSUE THREAD

**Issue by Geremia** [certbot/certbot#3622]
Why is certbot looking for `acme` 0.4.2 instead of using 0.9.1? (I'm using certbot 0.9.1.)

I get this when I run `certbot`:
```
Traceback (most recent call last):
  File "/usr/bin/certbot", line 11, in <module>
    load_entry_point('certbot==0.9.1', 'console_scripts', 'certbot')()
  File "/usr/lib64/python2.7/site-packages/certbot/main.py", line 732, in main
    plugins = plugins_disco.PluginsRegistry.find_all()
  File "/usr/lib64/python2.7/site-packages/certbot/plugins/disco.py", line 175, in find_all
    plugin_ep = PluginEntryPoint(entry_point)
  File "/usr/lib64/python2.7/site-packages/certbot/plugins/disco.py", line 34, in __init__
    self.plugin_cls = entry_point.load()
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2263, in load
    self.require(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 2280, in require
    items = working_set.resolve(reqs, env, installer)
  File "/usr/lib64/python2.7/site-packages/pkg_resources/__init__.py", line 861, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
VersionConflict: (acme 0.9.1 (/usr/lib64/python2.7/site-packages), Requirement.parse('acme==0.4.2'))
```

**Comment by pde** [comment]
Can you please tell us what OS and OS version you're running, what method you used to install Certbot 0.9.1, and (if you remember) what method you might have used to install `letsencrypt 0.4.2` in the past?

**Comment by pde** [comment]
I guess from the other ticket you mentioned Slackware 14.2...

**Comment by pde** [comment]
It looks like you might have a version of `python-letsencrypt-apache` or `python-letsencrypt-nginx` that's stuck at version 0.4.2; if you uninstall that (and optionally, install the latest `python-certbot-*` equivalent) this should be resolved.

**Comment by pde** [comment]
@willysr thanks for maintaining Slackware packages for us! Is there a way you can add a `conflicts:` label of some sort to prevent the old `letsencrypt` packages from misbehaving like this?

**Comment by willysr** [comment]
Hi @pde, thanks for the invitation.

about letsencrypt/certbot packaging, i don't think there's a problem since i'm using the same package on two public machines and it's working fine. I think the OP need to rebuilt all the deps to fix this issue.

Here's the SlackBuild script to build the certbot package
https://slackbuilds.org/slackbuilds/14.2/system/letsencrypt/letsencrypt.SlackBuild
i kept the package name letsencrypt and added a symlink letsencrypt -> certbot to help people that already used letsencrypt in the past

**Comment by Geremia** [comment]
@willysr I reinstalled all the dependencies, but I still get the same issue:
```
VersionConflict: (acme 0.9.1 (/usr/lib64/python2.7/site-packages), Requirement.parse('acme==0.4.2'))
```

**Comment by willysr** [comment]
@Geremia : can you list all SBo package installed on your system?
Also, is this on 14.2 or in current?

did you install letsencrypt manually in the past?

**Comment by Geremia** [comment]
@willnewby I'm on slackware-current and, yes, I did install letsencrypt both manually and with the SlackBuild in the past.

Here are the SBo packages I have installed:
```acousticbrainz-gui-0.1-x86_64-1_SBo
acousticbrainz-music-extractor-v2.1_beta2-x86_64-1_SBo
acpica-20160108-x86_64-1_SBo
android-tools-6.0.1_r43-x86_64-1_SBo
apache-ant-1.9.7-noarch-1_SBo
atop-2.2-x86_64-2_SBo
auctex-11.89-x86_64-1_SBo
audacity-c9fa500-x86_64-2_SBo
awstats-7.5-noarch-1_SBo
bibletime-2.11-x86_64-1_SBo
bitcoin-0.11.2-x86_64-1_SBo
blender-2.77a-x86_64-1_SBo
btrbk-0.23.3-x86_64-1_SBo
cairocffi-0.7.2-x86_64-1_SBo
camlp5-6.13-x86_64-1_SBo
cffi-1.8.3-x86_64-1_SBo
composer-1.2.0-noarch-1_SBo
configobj-4.7.2-x86_64-1_SBo
coq-8.5pl1-x86_64-1_SBo
cryptography-1.5-x86_64-1_SBo
dblatex-0.3.4-x86_64-1_SBo
eigen3-3.2.4-x86_64-1_SBo
enum34-1.1.6-x86_64-1_SBo
espeak-1.48.04-x86_64-1_SBo
fdupes-1.51-x86_64-2_SBo
fluid-soundfont-3.1_5-noarch-1_SBo
fontforge-20150824-x86_64-1_SBo
frescobaldi-2.0.13-x86_64-1_SBo
gflags-2.1.1-x86_64-1_SBo
glm-0.9.7.2-x86_64-1_SBo
gnome-python-2.28.1-x86_64-1_SBo
google-go-lang-1.7-x86_64-1_SBo
google-talkplugin-5.41.0.0-x86_64-1_SBo
gource-0.43-x86_64-1_SBo
gramps-3.4.3-x86_64-1_SBo
graphviz-2.38.0-x86_64-1_SBo
grpn-1.1.2-x86_64-1_SBo
guile1.8-1.8.8-x86_64-3_SBo
hal-flash-0.3.3-x86_64-1_SBo
haveged-1.9.1-x86_64-1_SBo
hidapi-0.8.0_rc1-x86_64-1_SBo
huludesktop-0.9.8-x86_64-2_SBo
idna-2.1-x86_64-1_SBo
iotop-0.6-x86_64-1_SBo
ipaddress-1.0.17-x86_64-1_SBo
jansson-2.9-x86_64-1_SBo
jq-1.4-x86_64-1_SBo
kdiff3-0.9.97-x86_64-1_SBo
ladr-2009_11A-x86_64-1_SBo
LanguageTool-3.4-noarch-1_SBo
leptonica-1.73-x86_64-1_SBo
letsencrypt-0.9.1-x86_64-1_SBo
libfilteraudio-20160614_2fc6695-x86_64-1_SBo
libgit2-0.23.4-x86_64-1_SBo
libiptcdata-1.0.4-x86_64-2_SBo
libmicrohttpd-0.9.42-x86_64-1_SBo
libofa-0.9.3-x86_64-2_SBo
libotr-4.1.1-x86_64-1_SBo
libupnp-1.6.17-x86_64-1_SBo
libyubikey-1.13-x86_64-1_SBo
lilypond-2.18.2-x86_64-1_SBo
memcached-1.4.25-x86_64-1_SBo
memcached-init-1.0.1-noarch-1_SBo
mftrace-1.2.18-x86_64-1_SBo
mock-1.0.1-x86_64-1_SBo
mod_geoip2-1.2.7-x86_64-1_SBo
modsecurity-apache-2.8.0-x86_64-1_SBo
mod_wsgi-4.4.6-x86_64-1_SBo
mozplugger-2.1.6-x86_64-1_SBo
mutagen-1.34.1-x86_64-1_SBo
ndg_httpsclient-0.4.0-x86_64-1_SBo
NetworkManager-openvpn-1.2.4-x86_64-1_SBo
niceshaper-1.0.0-x86_64-1_SBo
nodejs-5.4.0-x86_64-1_SBo
ocaml-4.03.0-x86_64-1_SBo
p7zip-16.02-x86_64-2_SBo
perl-FCGI-0.77-x86_64-1_SBo
php-memcache-3.0.8-x86_64-3_SBo
php-pgsql-5.6.24-x86_64-1_SBo
picard-1.3.2-x86_64-1_SBo
picard-plugins-20160206-x86_64-1_SBo
pidgin-otr-4.0.2-x86_64-1_SBo
pilkit-1.1.13-x86_64-1_SBo
popcorntime-0.3.9-x86_64-1_SBo
portaudio-v19_20140130-x86_64-1_SBo
postgresql-9.5.3-x86_64-1_SBo
potrace-1.13-x86_64-1_SBo
protobuf-2.6.1-x86_64-1_SBo
psutil-4.3.1-x86_64-1_SBo
pv-1.6.0-x86_64-1_SBo
pyasn1-0.1.9-x86_64-1_SBo
pycrypto-2.6.1-x86_64-1_SBo
pygame-1.9.1-x86_64-1_SBo
pyOpenSSL-16.1.0-x86_64-1_SBo
pyparsing-2.1.8-x86_64-1_SBo
pyrfc3339-1.0-x86_64-1_SBo
python2-pythondialog-3.4.0-x86_64-1_SBo
python3-pillow-3.0.0-x86_64-1_SBo
python-augeas-0.5.0-x86_64-1_SBo
python-configargparse-0.11.0-x86_64-1_SBo
python-parsedatetime-2.1-x86_64-1_SBo
python-requests-2.11.1-x86_64-1_SBo
python-xlib-0.14-x86_64-1_SBo
pytz-2014.10-x86_64-1_SBo
qdirstat-1.0-x86_64-1_SBo
qt5-webkit-5.7.0-x86_64-1_SBo
qTox-20160927_427176a-x86_64-1_SBo
qwt-6.1.3-x86_64-1_SBo
rawtherapee-4.2-x86_64-2_SBo
redshift-1.11-x86_64-1_SBo
retroshare-0.5.5c-x86_64-3_SBo
rng-tools-5-x86_64-1_SBo
rtmpdump-20150115_a107cef-x86_64-1_SBo
SDL2-2.0.4-x86_64-1_SBo
six-1.10.0-x86_64-1_SBo
soundtouch-1.9.2-x86_64-1_SBo
speex-1.2rc2-x86_64-5_SBo
splint-3.1.2-x86_64-1_SBo
sqlcipher-3.4.0-x86_64-1_SBo
steam-1.0.0.52-x86_64-1_SBo
sword-1.7.5a1-x86_64-1_SBo
t1utils-1.39-x86_64-1_SBo
tesseract-3.04.00-x86_64-1_SBo
testdisk-7.0-x86_64-1_SBo
texi2html-5.0-x86_64-1_SBo
TiMidity++-2.14.0-x86_64-3_SBo
tor-0.2.8.7-x86_64-1_SBo
torsocks-2.1.0-x86_64-1_SBo
toxcore-20160921_161ab46-x86_64-1_SBo
tvheadend-3.4patch1-x86_64-1_SBo
uemacs-20141208-x86_64-1_SBo
unclutter-1.09-x86_64-2_SBo
unetbootin-608-x86_64-1_SBo
vagrant-1.8.5-x86_64-1_SBo
virtualbox-5.0.14-x86_64-1_SBo
virtualbox-extension-pack-5.0.14-x86_64-1_SBo
virtualbox-kernel-5.0.14_4.4.23-x86_64-1_SBo
virtualenv-15.0.3-x86_64-1_SBo
werkzeug-0.9.4-x86_64-1_SBo
winetricks-20160109-noarch-1_SBo
wireshark-2.2.0-x86_64-1_SBo
wxPython-3.0.2.0-x86_64-2_SBo
xclip-0.12-x86_64-1_SBo
xephem-3.7.7-x86_64-1_SBo
yubikey-personalization-gui-3.1.23-x86_64-1_SBo
zenity-3.20.0-x86_64-1_SBo
zim-0.65-x86_64-1_SBo
zope.component-4.2.1-x86_64-1_SBo
```

**Comment by willysr** [comment]
Yes, it seems it messed up with pip packaging
best way is to stick with one method (SBo or pip).
Mixing them may result in inconsistent state

**Comment by Geremia** [comment]
@willnewby I ran `pip freeze | xargs pip uninstall -y` to clear all `pip` installs and then I ran `for i in `cat packages.txt`; do sbopkg -i $i; done` on all the requirements (which were many more than you mentioned in the SlackBuild):
 
"packages.txt":
```
cffi
configobj
cryptography
enum34
idna
ipaddress
letsencrypt
mock
ndg_httpsclient
psutil
pyasn1
pycparser
pyOpenSSL
pyparsing
pyrfc3339
python2-pythondialog
python-augeas
python-configargparse
python-parsedatetime
python-requests
pytz
six
werkzeug
zope.component
zope.event
zope.interface
```
Now it works!

@pde You may close this issue as solved. thank you

**Comment by willysr** [comment]
Glad to know that it solved your problem :)

about the number of packages, that's normal since the one listed in the SBo is only the first level dependencies, not all dependencies.

if you have sqg, you can have all of them by running sqg -p letsencrypt and it will generate a queue file with all the list of deps for that package.
