### ISSUE TITLE
Command line switches should override config file

### ISSUE THREAD

**Issue by starchy** [certbot/certbot#4441]
## I installed Certbot with (certbot-auto, OS package manager, pip, etc):   
apt/jessie-backports

## I ran this command and it produced this output:     
certbot certonly --manual --preferred-challenges dns -d <domain>  
Too many flags setting configurators/installers/authenticators 'webroot' -> 'manual'

## Certbot's behavior differed from what I expected because:

I have a predefined list of domains I keep up to date on this server with the webroot authenticator and cron listed out in a cli.ini file managed by our configuration management. I'm doing this manually because I'm adding a new domain to the server which can't be authenticated by webroot yet, so it needs to be setup differently with its own certificate for now.

It seems to make more sense for the UX to allow me to override the cli.ini than to require me to change it or create an alternate. Failing that, the error message should clarify the other source of the 'too many flags' - judging by the forums, this is a common cause for confusion.

**Comment by SwartzCr** [comment]
@schoen does this have to do with the cli.ini stuff you were documenting?

**Comment by SwartzCr** [comment]
possibly related to #4152 or #4107?

**Comment by SwartzCr** [comment]
Domains should not be listed in cli.ini if there are domains that need attention that are not mentioned in cli.ini
This is now documented via #4427
I'm in favor of closing this issue, since we generally discourage use of cli.ini - but would be happy to also clarify that error if @starchy thinks that'd still be helpful

**Comment by starchy** [comment]
Documentation that better pushes people away from using "domains = " sounds
like a good idea to me - this stems from writing configuration management
recipes that hinge on it in the early days of the Let's Encrypt client. I'm
sure we can find a better way to do that on our end.

**Comment by SwartzCr** [comment]
Yeah, I don't think we'll ever have the command line overwrite cli.ini info, since cli.ini is always a) written by the user and b) for all certs, where as the command line would be for only one cert.
I'm going to close this issue, but I'd be happy to work with you to figure out what you should do to best get your renewals in order. Also if you want to suggest improvements to the documentation please open new issue(s) for that & I'd be happy to help expand our documentation around this.

**Comment by bmw** [comment]
I just saw this issue.

My understanding is command line flags do override values in Certbot's INI file except in cases where different flags that interact are used (see https://github.com/bw2/ConfigArgParse/issues/58). Our dependencies for argument parsing don't/can't automatically handle this case for us, but I think we may want to reconsider reopening this issue and solving this problem.

@starchy, while not ideal, you should be able to work around the problem by using `-a/--authenticator <plugin name>` rather than `--<plugin name>` both in the configuration file and on the command line.

**Comment by starchy** [comment]
@bmw The strange issue I still see when using --authenticator and is that if I have `/etc/letsencrypt/cli.ini` with:

```
authenticator = webroot
webroot-path = /usr/share/nginx/www
rsa-key-size = 4096

```
and I have `/etc/letsencrypt/dns.ini` with:

```
authenticator = manual
rsa-key-size = 4096
preferred-challenges = dns
```

when I specify the latter config, certbot still appears to use the `webroot-path` from `cli.ini`:

```
$ sudo /opt/certbot-auto certonly -c /etc/letsencrypt/dns.ini -d example.com
/usr/share/nginx/www does not exist or is not a directory
```

Obviously I can change the contents of cli.ini, or move them to a different config, but this requires adding more special cases to our configuration management (and I'm curious if it exposes a certbot bug).

**Comment by bmw** [comment]
Unfortunately that's a known issue. I reported the problem upstream at bw2/ConfigArgParse#104 but haven't heard a response. We're considering dropping the libraries we use for this all together (see #4493), but it's a significant amount of work to do that refactoring and isn't on our immediate roadmap. Unfortunately, the solution right now is to move the problematic values out of the default config file and put them in another file or on the command line.

I'm also reopening this issue as I think the original problem here should be resolved.

**Comment by timwsuqld** [comment]
I'd love to see this resolved as well. It's expected behaviour of many common CLI applications, that even with a config file, you can override options on the CLI. `cli.ini` should set defaults for all domains, however we should be able to override those defaults on the CLI for an individual domain.

We have webroot for a number of domains that we want to keep using, but have 1 domain we want to use a different method for authenticating. Setting the authenticator on the CLI should override the `cli.ini` file.

**Comment by bmw** [comment]
configargparse's author described a way we can work around this behavior of their library at https://github.com/bw2/ConfigArgParse/issues/104#issuecomment-354884309 if someone is interested in writing up a PR. The PR would need tests and you can learn more about contributing to Certbot at https://certbot.eff.org/docs/contributing.html.

**Comment by timwsuqld** [comment]
I can't test the latest certbot releases due to the PPA being so far behind. I'll try and manually build newer packages and test, but I believe the issue is still present

**Comment by bmw** [comment]
Thanks @timwsuqld but there's no need to do that. I'm confident this issue is still there.
