### ISSUE TITLE
Passing arguments to httpd using apachectl is no longer supported.

### ISSUE THREAD

**Issue by jerwinrodriguez** [certbot/certbot#5439]
## My operating system is (include version):
CentOS Linux 7.3.1611

## I installed Certbot with (certbot-auto, OS package manager, pip, etc):
certbot-auto

## I ran this command and it produced this output:

certbot --authenticator standalone --installer apache --pre-hook "apachectl -k stop" --post-hook "apachectl -k start"

Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer apache
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
No names were found in your configuration files. Please enter in your domain
name(s) (comma and/or space separated)  (Enter 'c' to cancel): my.domain.name
Running pre-hook command: apachectl -k stop
Output from apachectl:
Passing arguments to httpd using apachectl is no longer supported.
You can only start/stop/restart httpd using this script.
If you want to pass extra arguments to httpd, edit the
/etc/sysconfig/httpd config file.

Obtaining a new certificate
Performing the following challenges:
http-01 challenge for my.domain.name
Waiting for verification...
Cleaning up challenges
Running post-hook command: apachectl -k start
Output from apachectl:
Passing arguments to httpd using apachectl is no longer supported.
You can only start/stop/restart httpd using this script.
If you want to pass extra arguments to httpd, edit the
/etc/sysconfig/httpd config file.

We were unable to find a vhost with a ServerName or Address of my.domain.name.
Which virtual host would you like to choose?
(note: conf files with multiple vhosts are not yet supported)
-------------------------------------------------------------------------------
1: ssl.conf                       |                       | HTTPS | Enabled
-------------------------------------------------------------------------------
Press 1 [enter] to confirm the selection (press 'c' to cancel): 1
Deploying Certificate for my.domain.name to VirtualHost /etc/httpd/conf.d/ssl.conf
Error while running apachectl graceful.

Job for httpd.service invalid.

Rolling back to previous server configuration...
Error while running apachectl graceful.

Job for httpd.service invalid.

Encountered exception during recovery
Error while running apachectl graceful.

Job for httpd.service invalid.
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/certbot/error_handler.py", line 100, in _call_registered
    self.funcs[-1]()
  File "/usr/lib/python2.7/site-packages/certbot/client.py", line 557, in _rollback_and_restart
    self.installer.restart()
  File "/usr/lib/python2.7/site-packages/certbot_apache/configurator.py", line 1793, in restart
    self._reload()
  File "/usr/lib/python2.7/site-packages/certbot_apache/configurator.py", line 1804, in _reload
    raise errors.MisconfigurationError(str(err))
MisconfigurationError: Error while running apachectl graceful.

Job for httpd.service invalid.

Error while running apachectl graceful.

Job for httpd.service invalid.

IMPORTANT NOTES:
 - An error occurred and we failed to restore your config and restart
   your server. Please submit a bug report to
   https://github.com/letsencrypt/letsencrypt
 - Congratulations! Your certificate and chain have been saved at:
   /etc/letsencrypt/live/my.domain.name/fullchain.pem
   Your key file has been saved at:
   /etc/letsencrypt/live/my.domain.name/privkey.pem
   Your cert will expire on 2018-04-16. To obtain a new or tweaked
   version of this certificate in the future, simply run certbot again
   with the "certonly" option. To non-interactively renew *all* of
   your certificates, run "certbot renew"

## Certbot's behavior differed from what I expected because:
The apache is not working as it should be?

## Here is the relevant nginx server block or Apache virtualhost for the domain I am configuring:
Not sure what this is but I use webmin.

**Comment by alasdairdc** [comment]
Running `sudo apachectl graceful` works fine in Debian Stretch, apache version `2.4.25-3+deb9u3`.  Does `apache` restart properly if you do it by hand?  You may have a misconfigured config being loaded.

**Comment by SwartzCr** [comment]
@jerwinrodriguez do you know what version of httpd you have?
@joohoi maybe we need to edit the comands for centos, wanna see if you can reproduce this?

**Comment by joohoi** [comment]
With a quick test, I am able to reproduce this. `apachectl graceful` fails when Apache is stopped.

To reproduce:
```
systemctl stop httpd
apachectl graceful
```
What works:
```
systemctl stop httpd
apachectl restart
```
and:
```
systemctl start httpd
apachectl graceful
```

For this use case when Apache is stopped for the Apache plugin used as installer, the `apachectl graceful` will fail. To fix this, we might have to change it to `apachectl restart`.

**Comment by SwartzCr** [comment]
@joohoi any progress on this? It seems important to prioritize

**Comment by joohoi** [comment]
Yes, the PR referenced above should fix this issue for the affected distributions. Thanks for reporting!

**Comment by thehackadmin** [comment]
I am having this same problem.  I was able to work around the issue during the initial install with this change:
`certbot --authenticator standalone --installer apache --pre-hook "systemctl stop httpd" --post-hook "systemctl start httpd"`

but the renew would not work.  Tried:
`certbot renew --dry-run --pre-hook "systemctl stop httpd" --post-hook "systemctl start httpd" --renew-hook="systemctl reload httpd"`

did not help.  returned:

```
Error while running apachectl graceful.

Job for httpd.service invalid.

Attempting to renew cert (tcm-ws.exmon.tcmis.com) from /etc/letsencrypt/renewal/tcm-ws.exmon.tcmis.com.conf produced an unexpected error: Error while running apachectl graceful.

Job for httpd.service invalid.
. Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/tcm-ws.exmon.tcmis.com/fullchain.pem (failure)
```

I expected renew-hook to replace the 'apachectl graceful' command, but it did not.  

additional notes:  I am working on:
CentOS Linux release 7.4.1708 (Core)
httpd.x86_64                      2.4.6-67.el7.centos.6          @updates
httpd-tools.x86_64                2.4.6-67.el7.centos.6          @updates
certbot.noarch                    0.21.1-1.el7                   @epel
python2-certbot.noarch            0.21.1-1.el7                   @epel
python2-certbot-apache.noarch     0.21.1-1.el7                   @epel

**Comment by OGiese** [comment]
Hello,

I am having the exact same error as thehackadmin.

**Comment by barreljan** [comment]
Same as @thehackadmin with Centos7

```
Error while running apachectl graceful.

Job for httpd.service invalid.

Attempting to renew cert (www.pc-mania.nl) from /etc/letsencrypt/renewal/www.pc-mania.nl.conf produced an unexpected error: Error while running apachectl graceful.

Job for httpd.service invalid.
. Skipping.
```
However, running it directly on the cli as per config file it seems to work:
```
[renewalparams]
authenticator = standalone
installer = apache
pre_hook = systemctl stop httpd
post_hook = systemctl start httpd
```
Like this:
certbot --authenticator standalone --installer apache -d www.pc-mania.nl --pre-hook "systemctl stop httpd" --post-hook "systemctl start httpd"

```
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer apache
Starting new HTTPS connection (1): acme-v01.api.letsencrypt.org
Cert is due for renewal, auto-renewing...
Running pre-hook command: systemctl stop httpd
Renewing an existing certificate
Performing the following challenges:
tls-sni-01 challenge for www.pc-mania.nl
Waiting for verification...
Cleaning up challenges
Running post-hook command: systemctl start httpd
Deploying Certificate for www.pc-mania.nl to VirtualHost /etc/httpd/conf.d/20_www.pc-mania.nl.conf
```

And he presto, the certificate is renewed without any problems.

I'm doing all the certs on the shared server now like this, but it is horrible work.

OS: Centos7.4.1708 core (kernel 3.10.0-693.17.1.el7.x86_64)
HTTPD: Apache/2.4.6
Python: 2.7.5
Certbot: 0.21.1

**Comment by thehackadmin** [comment]
I ran a yum update. Among other updates was certbot:
certbot.noarch                    0.22.0-1.el7

Same issues.

**Comment by crashdemons** [comment]
I'm now getting this issue with certbot or certbot-auto 0.23.0 (most up to date release/package) and apache on centos7.

I get the same error from the title when apachectl -t -D DUMP_INCLUDES is run, which seems to be located here:

https://github.com/certbot/certbot/blob/f43a95e9c123e9c8a83b7836d516bb2126045042/certbot-apache/certbot_apache/parser.py#L180

I would try to find a way to configure 'apache_cmd' but I couldn't find a way to do so from documentation, also using 'httpd' directly doesn't output anything when you use these parameters with it - so that doesn't seem viable.

What can I do about this?   I could presumably use certonly and install the cert myself but this is less than ideal.

**Comment by bmw** [comment]
@joohoi, can you take a look at this?

**Comment by sjaanus** [comment]
I have the problem on same setup, certbot-auto 0.23.0 with centos7. Everything on machine is yum updated.

**Comment by joohoi** [comment]
I think the discussion has diverged here, and we're talking about two different issues at the same time.

@crashdemons and @sjaanus could you elaborate a bit, preferably including the relevant `/var/log/letsencrypt/letsencrypt.log` file entries in pastebin or such. Also the command line used to run Certbot is relevant here. I'll reopen the issue for the time being.

The two different issues discussed here:
- Error when Apache is stopped, and is tried to restart with `apachectl graceful`, resulting in an error.
- Something related to not being able to pass parameters to apachectl.

**Comment by crashdemons** [comment]
`./certbot-auto --apache -d beta.meme.tips`  (similar to the command on your repo documentation)
or the same using the current certbot package via yum - the only differences in the log are the location of the python files from /opt/eff.org/venv/lib... to /usr/lib/... - same errors.

this also occurs also if I run without specifying the domain explicitly for the interactive prompt, among others.

certbot-auto log: https://pastebin.com/500PKpBR

dist info: https://pastebin.com/nhsRAtFD

If I've misconfigured something then I'm sorry for wasting your time, but I've been trying to figure out what is going on for the longest time.  This worked fine before...

**Comment by joohoi** [comment]
Ok, so you two are experiencing separate issues.

The issue that @sjaanus is experiencing was in fact fixed in Certbot 0.23.0, more specifically in PR #5500 updating to the most recent version should fix your problem. Are you using standalone plugin as authenticatior, as this issue should only surface, if Apache is not running when Certbot tries to restart it by issuing `apachectl graceful`? 

For the problem @crashdemons sees, it looks like there's something weird going on with the `apachectl` command. Python seems to throw either `OSError` or `ValueError` (most likely OSError) when trying to run `apachectl -t -D DUMP_INCLUDES`. Are you able to run the command manually (regardless of the output)?

**Comment by sjaanus** [comment]
@joohoi 

I am not fully sure what package I should have, it seems that I have installed certbot 0.22.2, but it says it is latest version.

`yum info cerbot`
```
Installed Packages
Name        : certbot
Arch        : noarch
Version     : 0.22.2
Release     : 1.el7
Size        : 23 k
Repo        : installed
From repo   : epel
Summary     : A free, automated certificate authority client
URL         : https://pypi.python.org/pypi/certbot
License     : ASL 2.0
Description : certbot is a free, automated certificate authority that aims
            : to lower the barriers to entry for encrypting all HTTP traffic on the internet.

```

When I checked the webpage, it said that I need cerbot-apache, but when installing that I get.

```
[root@CentOS-74-64-minimal ~]#  yum install certbot-apache
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centosmirror.netcup.net
 * epel: mirror.de.leaseweb.net
 * extras: centosmirror.netcup.net
 * updates: centosmirror.netcup.net
Package python2-certbot-apache-0.22.2-1.el7.noarch already installed and latest version
Nothing to do

```

**Comment by joohoi** [comment]
I'll try to find the information about the ETA for the latest version to land CentOS EPEL repos for you.

Meanwhile, for a quick workaround:
Is there a reason for stopping Apache before running Certbot, via pre-hook functionality or otherwise? If you would be able to do keep Apache running, this issue shouldn't affect you.

If you think this approach would be feasible, and you have for reason or another set a prehook script to stop Apache before running Certbot, those pre- and post-hook commands should be editable in `/etc/letsencrypt/renewal/yourdomain.tld.conf`.

**Comment by sjaanus** [comment]
@joohoi 

I just checked and it appears that my cert got updated 2 days ago, it seems while I was testing different things, something got it updated, but I am not sure what exactly. Anyways, this is good enough for next 3 months.

Thanks for help, I hope you can sort this thing out meanwhile.

**Comment by crashdemons** [comment]
@joohoi yes, the command can be 'ran' in the same user/environment.  See here:  https://pastebin.com/h3GqVnYt

**Comment by crashdemons** [comment]
@joohoi After adding some additional lines to debug which exception was being caught on parser.py#L225 (your logger entry doesn't print the caught exception),   

I determined the exception being caught is `OSError: 12 - Cannot allocate memory` (errno - sterror)

Which is odd because I have plenty of free memory and there shouldn't be any permission restrictions on the process.

**Comment by thehackadmin** [comment]
I updated to `certbot.noarch                    0.22.2-1.el7                   @epel`.  Perhaps I do not understand, but this does not seem solved for me.  

Just to be clear:  I got apache running with a simple html page.  I am able to start/stop/restart/reload apache using the systemctl command.  eg: `systemctl stop httpd`.  With apache running, the command `certbot renew --dry-run` fails with:
```
Error while running apachectl graceful.
...
Running post-hook command: apachectl -k start
Output from apachectl:
Passing arguments to httpd using apachectl is no longer supported.
You can only start/stop/restart httpd using this script.
If you want to pass extra arguments to httpd, edit the
/etc/sysconfig/httpd config file.
```

Once this happens, the systemctl commands no longer work until I kill -15 the apache process... but he apache threads continue to serve pages also...  

So am I being dense?  (I hate it when I do that...)  Is there a better Issue I should be watching?  

results of certbot renew --dry-run:
```
[root@exmon01 ~]# certbot renew --dry-run
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/exmon.com.conf
-------------------------------------------------------------------------------
Cert is due for renewal, auto-renewing...
Plugins selected: Authenticator standalone, Installer apache
Starting new HTTPS connection (1): acme-staging-v02.api.letsencrypt.org
Running pre-hook command: apachectl -k stop
Output from apachectl:
Passing arguments to httpd using apachectl is no longer supported.
You can only start/stop/restart httpd using this script.
If you want to pass extra arguments to httpd, edit the
/etc/sysconfig/httpd config file.

Renewing an existing certificate
Performing the following challenges:
http-01 challenge for tcm-ws.exmon.com
http-01 challenge for wheee.com
http-01 challenge for www.wheee.com
Waiting for verification...
Cleaning up challenges
Error while running apachectl graceful.

Job for httpd.service invalid.

Attempting to renew cert (exmon.com) from /etc/letsencrypt/renewal/exmon.com.conf produced an unexpected error: Error while running apachectl graceful.

Job for httpd.service invalid.
. Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/exmon.com/fullchain.pem (failure)

-------------------------------------------------------------------------------
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates below have not been saved.)

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/exmon.com/fullchain.pem (failure)
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates above have not been saved.)
-------------------------------------------------------------------------------
Running post-hook command: apachectl -k start
Output from apachectl:
Passing arguments to httpd using apachectl is no longer supported.
You can only start/stop/restart httpd using this script.
If you want to pass extra arguments to httpd, edit the
/etc/sysconfig/httpd config file.

1 renew failure(s), 0 parse failure(s)
You have mail in /var/spool/mail/root
[root@infprd-exmon01 ~]# certbot renew --dry-run
Saving debug log to /var/log/letsencrypt/letsencrypt.log

-------------------------------------------------------------------------------
Processing /etc/letsencrypt/renewal/exmon.com.conf
-------------------------------------------------------------------------------
Cert is due for renewal, auto-renewing...
Plugins selected: Authenticator standalone, Installer apache
Starting new HTTPS connection (1): acme-staging-v02.api.letsencrypt.org
Running pre-hook command: apachectl -k stop
Output from apachectl:
Passing arguments to httpd using apachectl is no longer supported.
You can only start/stop/restart httpd using this script.
If you want to pass extra arguments to httpd, edit the
/etc/sysconfig/httpd config file.

Renewing an existing certificate
Performing the following challenges:
http-01 challenge for exmon.com
http-01 challenge for wheee.com
http-01 challenge for www.wheee.com
Waiting for verification...
Cleaning up challenges
Error while running apachectl graceful.

Job for httpd.service invalid.

Attempting to renew cert (exmon.com) from /etc/letsencrypt/renewal/exmon.com.conf produced an unexpected error: Error while running apachectl graceful.

Job for httpd.service invalid.
. Skipping.
All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/exmon.com/fullchain.pem (failure)

-------------------------------------------------------------------------------
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates below have not been saved.)

All renewal attempts failed. The following certs could not be renewed:
  /etc/letsencrypt/live/exmon.com/fullchain.pem (failure)
** DRY RUN: simulating 'certbot renew' close to cert expiry
**          (The test certificates above have not been saved.)
-------------------------------------------------------------------------------
Running post-hook command: apachectl -k start
Output from apachectl:
Passing arguments to httpd using apachectl is no longer supported.
You can only start/stop/restart httpd using this script.
If you want to pass extra arguments to httpd, edit the
/etc/sysconfig/httpd config file.

1 renew failure(s), 0 parse failure(s)
You have mail in /var/spool/mail/root
```

And the log file includes:
```
2018-04-16 22:52:06,940:ERROR:certbot.util:Error while running apachectl graceful.

Job for httpd.service invalid.

2018-04-16 22:52:06,940:WARNING:certbot.renewal:Attempting to renew cert (exmon.com) from /etc/letsencrypt/renewal/exmon.com.conf produced an unexpected error: Error while running apachectl graceful.

Job for httpd.service invalid.
. Skipping.
2018-04-16 22:52:06,942:DEBUG:certbot.renewal:Traceback was:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/certbot/renewal.py", line 422, in handle_renewal_request
    main.renew_cert(lineage_config, plugins, renewal_candidate)
  File "/usr/lib/python2.7/site-packages/certbot/main.py", line 1112, in renew_cert
    installer.restart()
  File "/usr/lib/python2.7/site-packages/certbot_apache/configurator.py", line 1989, in restart
    self._reload()
  File "/usr/lib/python2.7/site-packages/certbot_apache/configurator.py", line 2000, in _reload
    raise errors.MisconfigurationError(str(err))
MisconfigurationError: Error while running apachectl graceful.

Job for httpd.service invalid.
```
Status of apache:
```
[root@exmon01 httpd]# systemctl status httpd
● httpd.service - The Apache HTTP Server
   Loaded: loaded (/usr/lib/systemd/system/httpd.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2018-04-16 23:33:01 UTC; 12s ago
     Docs: man:httpd(8)
           man:apachectl(8)
  Process: 4095 ExecStop=/bin/kill -WINCH ${MAINPID} (code=exited, status=1/FAILURE)
  Process: 2843 ExecReload=/usr/sbin/httpd $OPTIONS -k graceful (code=exited, status=0/SUCCESS)
  Process: 4056 ExecStart=/usr/sbin/httpd $OPTIONS -DFOREGROUND (code=exited, status=0/SUCCESS)
 Main PID: 4056 (code=exited, status=0/SUCCESS)
   Status: "Total requests: 0; Current requests/sec: 0; Current traffic:   0 B/sec"

Apr 16 23:32:30 infprd-exmon01 systemd[1]: Starting The Apache HTTP Server...
Apr 16 23:32:30 infprd-exmon01 systemd[1]: Started The Apache HTTP Server.
Apr 16 23:33:01 infprd-exmon01 kill[4095]: kill: cannot find process ""
Apr 16 23:33:01 infprd-exmon01 systemd[1]: httpd.service: control process exited, code=exited status=1
Apr 16 23:33:01 infprd-exmon01 systemd[1]: Unit httpd.service entered failed state.
Apr 16 23:33:01 infprd-exmon01 systemd[1]: httpd.service failed.
Apr 16 23:33:07 infprd-exmon01 systemd[1]: Unit httpd.service cannot be reloaded because it is inactive.
```

apache error log:
```
[Mon Apr 16 23:40:07.417978 2018] [mpm_prefork:notice] [pid 4117] AH00169: caught SIGTERM, shutting down
[Mon Apr 16 23:40:30.231329 2018] [core:notice] [pid 4203] SELinux policy enabled; httpd running as context system_u:system_r:httpd_t:s0
[Mon Apr 16 23:40:30.233080 2018] [suexec:notice] [pid 4203] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Mon Apr 16 23:40:30.234878 2018] [ssl:warn] [pid 4203] AH02292: Init: Name-based SSL virtual hosts only work for clients with TLS server name indication support (RFC 4366)
[Mon Apr 16 23:40:30.256629 2018] [auth_digest:notice] [pid 4203] AH01757: generating secret for digest authentication ...
[Mon Apr 16 23:40:30.257506 2018] [lbmethod_heartbeat:notice] [pid 4203] AH02282: No slotmem from mod_heartmonitor
[Mon Apr 16 23:40:30.259284 2018] [ssl:warn] [pid 4203] AH02292: Init: Name-based SSL virtual hosts only work for clients with TLS server name indication support (RFC 4366)
[Mon Apr 16 23:40:30.262466 2018] [mpm_prefork:notice] [pid 4203] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips configured -- resuming normal operations
[Mon Apr 16 23:40:30.262493 2018] [core:notice] [pid 4203] AH00094: Command line: '/usr/sbin/httpd -D FOREGROUND'
[Mon Apr 16 23:41:06.197302 2018] [mpm_prefork:notice] [pid 4203] AH00169: caught SIGTERM, shutting down
[Mon Apr 16 23:41:12.619465 2018] [core:notice] [pid 4263] SELinux policy enabled; httpd running as context unconfined_u:system_r:httpd_t:s0
[Mon Apr 16 23:41:12.620866 2018] [suexec:notice] [pid 4263] AH01232: suEXEC mechanism enabled (wrapper: /usr/sbin/suexec)
[Mon Apr 16 23:41:12.622636 2018] [ssl:warn] [pid 4263] AH02292: Init: Name-based SSL virtual hosts only work for clients with TLS server name indication support (RFC 4366)
[Mon Apr 16 23:41:12.647349 2018] [auth_digest:notice] [pid 4264] AH01757: generating secret for digest authentication ...
[Mon Apr 16 23:41:12.648401 2018] [lbmethod_heartbeat:notice] [pid 4264] AH02282: No slotmem from mod_heartmonitor
[Mon Apr 16 23:41:12.650281 2018] [ssl:warn] [pid 4264] AH02292: Init: Name-based SSL virtual hosts only work for clients with TLS server name indication support (RFC 4366)
[Mon Apr 16 23:41:12.653072 2018] [mpm_prefork:notice] [pid 4264] AH00163: Apache/2.4.6 (CentOS) OpenSSL/1.0.2k-fips configured -- resuming normal operations
[Mon Apr 16 23:41:12.653104 2018] [core:notice] [pid 4264] AH00094: Command line: '/usr/sbin/httpd'
```
Yeah... it just ends there.

**Comment by joohoi** [comment]
There seems to be two different issues here. The error with running `apachectl graceful` should be fixed in Certbot 0.23, which should be available for you when your distributions packages get updated.

However you seem to have a lot going on in your renewal configuration for this domain. Pre- and post hook commands that seem to be failing, for example. If you don't have a need to use standalone authenticator, the simplest fix would probably be to modify your `/etc/letsencrypt/renewal/exmon.com.conf` as follows:

Change `authenticator` to apache, and comment out pre- and post-hooks. Leave the other values as they are.
```
...
[renewalparams]
authenticator = apache
#pre_hook = apachectl -k stop
#post_hook = apachectl -k start
...
```

I believe this change would fix the issue for you.

**Comment by thehackadmin** [comment]
OK, I look forward to trying it out with 0,23 when I get it... however:

I am getting the `apachectl graceful` message when apache ***is*** running.  I tested this several times yesterday.  

I got apache running with a simple html page. I am able to start/stop/restart/reload apache using the systemctl command. eg: `systemctl stop httpd`.  ***With apache running***, the command `certbot renew --dry-run` fails with the `apachectl graceful` message.

**Comment by joohoi** [comment]
The pasted output suggests that you have configured Certbot with pre-hook at least *trying* to stop Apache2:
`Running pre-hook command: apachectl -k stop`

I would suggest checking your renewal configuration as instructed in https://github.com/certbot/certbot/issues/5439#issuecomment-381870072

Even when 0.23 fixes the `apachectl graceful` issue, your configured post-hook:
`Running post-hook command: apachectl -k start`

could error out, as Apache would be running.

**Comment by thehackadmin** [comment]
Ahhh...  yes...  That is the kick in my pants i needed.  In trying to figure this out in earlier version i added lines to renewal/exmon.com.conf:
```
pre_hook = apachectl -k stop
post_hook = apachectl -k start
```
and I failed to remove them when they did not work.  I still have a problem, but it looks unrelated.  

Thank you for your patience.

**Comment by johnnytemp** [comment]
> 
> 
> With a quick test, I am able to reproduce this. `apachectl graceful` fails when Apache is stopped.
> 
> To reproduce:
> 
> ```
> systemctl stop httpd
> apachectl graceful
> ```
> 
> What works:
> 
> ```
> systemctl stop httpd
> apachectl restart
> ```
> 
> and:
> 
> ```
> systemctl start httpd
> apachectl graceful
> ```
> 
> For this use case when Apache is stopped for the Apache plugin used as installer, the `apachectl graceful` will fail. To fix this, we might have to change it to `apachectl restart`.

I have same issue on CentOS 7.7 with apache 2.4.6 (CentOS). (yum updated to latest, as of 2019-11-05)

Whenever the apache is stopped (e.g. with `systemctl stop httpd` or `apachectl stop`), doing a `apachectl graceful` or `systemctl reload httpd` always get this error:

    Job for httpd.service invalid.

However, calling e.g. `apachectl start` got no error. Seems currently, apache must be running for `apachectl graceful` or `systemctl reload httpd` to work. Better need a fix.
