### ISSUE TITLE
nginx: support *_by_lua_block directives

### ISSUE THREAD

**Issue by alexzorin** [certbot/certbot#9066]
Certbot v1.20.0.

See https://community.letsencrypt.org/t/bug-init-by-lua-block-and-certbot/162952

Something like this fails to parse:

```nginx
        init_by_lua_block {
                print('hi')
        }
```

These directives contain Lua code, but Certbot's parser tries to interpret the body as nginx configuration and fails.

**Comment by pmontrasio** [comment]
Also `content_by_lua_block`  and probably every directive containing code that it cannot parse.

Furthermore the parser fails with the wrong message
```
Could not parse file: /etc/nginx/sites-enabled/default.conf due to Expected string_end, found 'server'  (at char 0), (line:1, col:1)
```

for a file starting with `server {`

It should fail with an error about the directive it cannot understand.

A fix could be skipping either the line or the `{}` block for the directive it doesn't understand.

**Comment by DonTsipa** [comment]
Hey, I fixed it in  https://github.com/certbot/certbot/pull/9409

**Comment by kzar** [comment]
For what it's worth I hit this today. If handling Lua blocks isn't practical, perhaps certbot could at least display a warning and fail gracefully (and maybe even mention this issue) when they are detected? At least that would point folks in the right direction.

**Comment by alexzorin** [comment]
Yep. That's a good idea. Whether or not proper lua parsing support is eventually added, it would be good to raise a friendly error when encountering `*_by_lua_*` blocks and redirecting the user to alternate actions.

I had a quick go at this:

```diff
diff --git a/certbot-nginx/certbot_nginx/_internal/nginxparser.py b/certbot-nginx/certbot_nginx/_internal/nginxparser.py
index 1c74cd367..dbecd59e7 100644
--- a/certbot-nginx/certbot_nginx/_internal/nginxparser.py
+++ b/certbot-nginx/certbot_nginx/_internal/nginxparser.py
@@ -56,6 +56,15 @@ class RawNginxParser:
     token = paren_quote_extend | tokenchars | quoted
 
     whitespace_token_group = space + token + ZeroOrMore(required_space + token) + space
+
+    @whitespace_token_group.add_parse_action
+    def not_lua(results: ParseResults):
+        if str(results[1]).endswith('_by_lua_block'):
+            raise RuntimeError(
+                "The nginx configuration contained *_by_lua_block directives, which are not "
+                "supported by Certbot's --nginx plugin. Consider using the --webroot plugin, "
+                "manually installing the certificate, or using *_by_lua_file instead.")
+
     assignment = whitespace_token_group + semicolon
 
     comment = space + Literal('#') + restOfLine
```

and it produces output like:

<img width="1456" alt="image" src="https://user-images.githubusercontent.com/311534/202803717-646ab5b2-5889-4857-bcc0-26b31f5c6811.png">

I am not sure whether that's the best way to wrangle `pyparsing` into doing this though.

**Comment by kzar** [comment]
> I had a quick go at this...
> ...and it produces output like:

Nice one. I can't comment on your approach (I'm not familiar with that code at all and don't have time to look into it right now), but that example output would be very helpful. If certbot had output that to me yesterday, I would have saved a bunch of time figuring out what had gone wrong. The error message I received was so misleading that I ended up bisecting the config to figure out which part confused certbot.

**Comment by madhusudan** [comment]
Looks like issue still exists in 2024!, in latest nginx 1.24 and certbot ver 2.8.0

nginx syntax is fine but certbot not able to accept below line and throwing error.

`access_by_lua_block { require('cas').forceAuthentication() }`

Error is 
`Could not parse file: /etc/nginx/sites-enabled/default due to Expected string_end, found 'server'  (at char 875), (line:21, col:1)`

**Comment by toh2526** [comment]
Same as mine,
issue also found in Ubuntu 20.04
nginx 1.18 and certbot 2.9.0

Nginx syntax is fine by `nginx -t`
but certbot not able to accept below line and throwing an error with nginx configs with:
`content_by_lua_block` and `access_by_lua_file`

Error:
Could not parse file: /etc/nginx/sites-enabled/my_site_config due to Expected string_end, found 'server'  (at char 1), (line:2, col:1)

**Comment by Ryuno-Ki** [comment]
+1.

I can successfully request a new certificate but there's these errors filling my screen when doing so (for the first round).
